services:
    symfony-api:
        container_name: symfony-api
        build:
            context: .
            target: frankenphp_dev
        ports:
            - "8000:80"
            - "4443:443"
        volumes:
            - ./:/app
            - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
            - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
        depends_on:
            - postgres-db
        networks:
            - backend
        environment:
            - SERVER_NAME=:80
            - FRANKENPHP_WORKER_CONFIG=watch
    # Configured in Caddyfile           - APP_RUNTIME=Runtime\\FrankenPhpSymfony\\Runtime
        extra_hosts:
            - host.docker.internal:host-gateway

    postgres-db:
        container_name: postgres-db
        image: postgres:latest
        environment:
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_NAME}"
        ports:
            - "${DB_PORT}:5432"
        networks:
            - backend
        volumes:
            - db:/data/postgres
            - caddy_data:/data
            - caddy_config:/config

networks:
    backend:
        name: backend-network
        driver: bridge

volumes:
    db:
    caddy_data:
    caddy_config:
