controllers:
    resource:
        path: ../../src/ShortLink/Infrastructure/Symfony/Controller/
        namespace: App\ShortLink\Infrastructure\Symfony\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute
